### ISSUE TITLE
\faLanguage in languages section doesnt work

### ISSUE THREAD

**Issue by mahidharN** [darwiin/yaac-another-awesome-cv#20]
adding `\faLanguage` doesnt render the icon as it was shown in other sample pdfs. 

I was wondering how one would debug this issue. Where is `faLanguage` compiles to a icon?

_help wanted_

**Comment by bawantha** [comment]
I think issue with fontawsome5 this CV doesn't support it

**Comment by darwiin** [comment]
Can't reproduce the issue. The font awesome icon is correctly showing
1. on Circle CI build
1. on my environment
