### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Pilonepic** [darwiin/yaac-another-awesome-cv#23]
Hi, I know I am very new to programming and this must sound like a relly easy question, but I don't understand how to change the color for Titles. If you could explain, that would be really nice. Thanks!

**Comment by darwiin** [comment]
Predefined options come with the template:

1. green
1. red
1. indigo
1. orange
1. monochrome

All you need to do is to add the color in the document class declaration with one of the previous one given`\documentclass[localFont,alternative,<color>]{yaac-another-awesome-cv}`.

For example you could use `\documentclass[localFont,alternative,monochrome]{yaac-another-awesome-cv}` for the monochrome version.
