### ISSUE TITLE
fontawseome5 is not working

### ISSUE THREAD

**Issue by bawantha** [darwiin/yaac-another-awesome-cv#24]
LaTeX Error: File `fontawesome5.sty' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
   
l.51 \RequirePackage
                  {hyperref}
*** (cannot \read from terminal in nonstop modes

**Comment by darwiin** [comment]
Hi, did you check that you have the Fonteawesome5 package installed on your system ?

**Comment by azdobylak** [comment]
Had the same issue. In my case it worked when I had replaced: `\RequirePackage[fixed]{fontawesome5}` => `\RequirePackage{fontawesome}`.
I am using [ttf-font-awesome 5.7.0-1](https://www.archlinux.org/packages/community/any/ttf-font-awesome/), but no idea if AUR package is not properly deployed or there is wrong assumption in projects requirements.

**Comment by darwiin** [comment]
The problem is with the `fontawesome5` latex package version, not the font version. The `fixed` option has been added with the     * `5.4.1 fontawesome5` package

**Comment by bawantha** [comment]
> Hi, did you check that you have the Fonteawesome5 package installed on your system ?

Actually, I did it on Overleaf I think they have installed.

**Comment by darwiin** [comment]
Could you double check with them. I'm pretty sure they use a old live tex distribution that don't include `fonteawesome5` package. In fact that's why I only share the legacy branch on overleaf...
