### ISSUE TITLE
Error when compiling with luatex.

### ISSUE THREAD

**Issue by kris-singh** [darwiin/yaac-another-awesome-cv#25]
! Undefined control sequence.
l.78 \DeclareUnicodeCharacter
                           {00E9}{\'{e}}
? 

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.78 \DeclareUnicodeCharacter{0
                             0E9}{\'{e}}
? 
Package hyperref Info: Option `breaklinks' set `true' on input line 114.
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not fou
nd: fonts/SourceSansPro-Light.".(save: /Users/krishna.singh/Library/texlive/2018
/texmf-var/luatex-cache/generic/fonts/otl/sourcesanspro-light.lua)(save: /Users/
krishna.singh/Library/texlive/2018/texmf-var/luatex-cache/generic/fonts/otl/sour
cesanspro-light.luc)
*************************************************

and someother errors 

Underfull \hbox (badness 10000) in paragraph at lines 15--11

 []

Underfull \hbox (badness 10000) in paragraph at lines 20--20

 []

LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 26.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 26.

Underfull \hbox (badness 10000) in paragraph at lines 26--26

 []

) (./section_references.tex
Overfull \hbox (17.99348pt too wide) in paragraph at lines 21--21
[][] 
 []

) [2]

**Comment by darwiin** [comment]
It looks like the `SourceSansPro-Light` font is missing... Could you please check that the font is present ?
