### ISSUE TITLE
\today date format issues.

### ISSUE THREAD

**Issue by bugcy013** [darwiin/yaac-another-awesome-cv#29]
Hi Guys,

When I use `{\today}` it's rendering `25 MARS 2019`.  I am not sure how to fix this.  it's adding extra   `S` `MARS` to `MAR` can you please guide me. How to fix this.

-Dhanasekaran.

**Comment by darwiin** [comment]
Hi,

Could you please try this ? I can't build right now, but I think this will solve your problem.

```
\makecvfooter
	{\textsc{\selectlanguage{english}\today}} 
	{\textsc{Christophe Roger - CV}}
        {\thepage}
```

Christophe.

**Comment by bugcy013** [comment]
Hi @darwiin 

now it's working. now it's rendering `MARCH 25, 2019`  Thanks you. 

-Dhanasekaran.
