### ISSUE TITLE
yaac-another-awesome-cv

### ISSUE THREAD

**Issue by shantanu1402** [darwiin/yaac-another-awesome-cv#3]
Hello Christophe Roger,
                                     Thank you so much for providing this nice template.  I am planning to use this with some customization. Please help me in this regard. Following are my initial questions: (a) I want to convert the font color of the entire document to black, how to do that ? I am able to do some part black.But, section titles and the personal details are still in blue. How to make this change ?, (b) also I want to remove various symbols at various section heading, how do I do that ?(c) also I want to suppress the box around webpage , e-mail id showing hyperlinks, how to do this ? Please help me.
with warm regards,
Shantanu

**Comment by darwiin** [comment]
Hi,

Thanks for opening an issue.

I just add an option to use only black color:
``\documentclass[localFont,alternative,monochrome]{yaac-another-awesome-cv}

**Comment by shantanu1402** [comment]
Hi Christophe Roger,
                              Thank you so much for your help. I have few more questions on this template as I am trying to customize it to some extent. I am willing to take your help by asking questions as and when they come across. I shall be grateful if you reply them whenever possible. Please tell me how can I add skype icon and skype id in this template next to the contact number. Also I have observed that there is an error in the latest template (v1.8.0) that you have shared. It is showing error both in overleaf and also while running in the system. Please have a look on that.
with warm regards,
Shantanu

**Comment by shantanu1402** [comment]
Hi,
    Sorry I forgot to mention that I have accommodated your suggestions in the template and they are working great. Thank you once again.
with warm regards,
Shantanu

**Comment by darwiin** [comment]
Hi @shantanu1402 ,
Please see #4 for an answer to your question regarding a skype entry on your personal informations.

**Comment by shantanu1402** [comment]
Thank you so much
