### ISSUE TITLE
Is there any icon for "Publication"?

### ISSUE THREAD

**Issue by phosseini** [darwiin/yaac-another-awesome-cv#31]
I'm wondering if there is any icon/image to be used in the head of "Publication" section? (I'm adding the publication section myself.)

> [UPDATE] I found the answer to my question, there is a great collection of icons to be used [here](http://mirror.neu.edu.cn/CTAN/fonts/fontawesome/doc/fontawesome.pdf).

**Comment by darwiin** [comment]
These are the icons used in this template Fontawesome 5 [here](http://mirror.lagoon.nc/pub/ctan/fonts/fontawesome5/doc/fontawesome5.pdf) and [here](https://fontawesome.com/)
