### ISSUE TITLE
change language to chinese

### ISSUE THREAD

**Issue by 77QingLiu** [darwiin/yaac-another-awesome-cv#36]
Hi darwiin, thanks for you building such an amazing resume template
I tried to change  `\RequirePackage[english, chinese]{babel}` in the yaac-another-awesome-cv file, but it doesn't work.

the following error appeared
```
 /usr/local/texlive/2017/texmf-dist/tex/generic/babel/babel.sty, line 389
Package babel Error: Unknown option `chinese'. Either you misspelled it  or the language definition file chinese.ldf was not found.
```
Could you help me fix it ?
Thank you!

**Comment by darwiin** [comment]
I don't think babel support chinese this way out of the box....

**Comment by 77QingLiu** [comment]
Yes...I use the xeCJK instead `\usepackage{xeCJK}`

**Comment by gaxuhongyu** [comment]
@77QingLiu 哥们，你中文支持成功了么？求指导，一直没弄出来

**Comment by LiZi-77** [comment]
you can add `\usepackage[UTF8]{ctex}` after `\documentclass` line to support Chinese
