### ISSUE TITLE
Reduce \hspace between minipage{} environment

### ISSUE THREAD

**Issue by 77QingLiu** [darwiin/yaac-another-awesome-cv#37]
there is too much blank space in the minipage paragraph, how can I reduce the blank?
![image](https://user-images.githubusercontent.com/32193271/58966176-621ef500-87e4-11e9-9af7-4fe8da4ccb58.png)
Thanks

**Comment by darwiin** [comment]
Hello @77QingLiu ,

Could you please post the full page ?

Regards.

**Comment by 77QingLiu** [comment]
here is the full page
![image](https://user-images.githubusercontent.com/32193271/58996584-6ae6e980-882b-11e9-8c9e-4905e7947676.png)

there are too much space here

**Comment by darwiin** [comment]
So, could you show me what kind of output you did expect from your example ? I can't figure out how to make it differently...

**Comment by 77QingLiu** [comment]
@darwiin I want the margin on the left of the text to be narrow, which means I can put more text on each line

**Comment by 77QingLiu** [comment]
@darwiin Thanks very much for the update. The left column size could be changed now. But the number of words per line is fixed which makes the whole line moves left when reducing the left column size, but not increase words per line. I'm wondering is there are any options to increase words per line?

**Comment by darwiin** [comment]
Did'nt see this...

**Comment by darwiin** [comment]
@77QingLiu Thanks for waiting. It was difficult to understand what was the problem. I think this new fix is the good one, let me know if that solve the problem.
