### ISSUE TITLE
Reduce vertical spacing created by \emptySeparator

### ISSUE THREAD

**Issue by KrishnaDeepak6** [darwiin/yaac-another-awesome-cv#40]
Can we reduce the spacing created by \emptySeparator? Was hoping to compress this vertical space and add more lines on the page.

Tried using alternate commands like \vspace{-5mm}, \\*, \\linebreak etc. but they disturb the alignments in the tables that follow and are not useful.

Thanks!
<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/52364837/60391561-dbbdb080-9b0e-11e9-8057-bc200a539553.PNG">

**Comment by darwiin** [comment]
Sorry for not answering earlier, will try to give you a workaround soon. Do you still need it ?

**Comment by KrishnaDeepak6** [comment]
Hi Christophe, Thanks for the response. Will be helpful to have the fix. Thank you! :)

**Comment by darwiin** [comment]
Hi @KrishnaDeepak6 feel free to re-open the issue if this is not what you were waiting for...
