### ISSUE TITLE
Is it possible to double-column?

### ISSUE THREAD

**Issue by jpinzon408** [darwiin/yaac-another-awesome-cv#42]
I like your cv, but I am interested in having it in a double-column to reduce the space and have the possibility of including more sections, is it possible? And how can it be done?

**Comment by darwiin** [comment]
Hi,
Thanks for your message, it could be done, but I think is more a new project that an evolution of this one. I will try to have a look as soon as I'll get more time.

For a two column template, did you try this one ? https://github.com/liantze/AltaCV
