### ISSUE TITLE
Two column Support for same section 

### ISSUE THREAD

**Issue by pbisaria007** [darwiin/yaac-another-awesome-cv#53]
How to use two columns in same section?

**Comment by darwiin** [comment]
Hi,

I would have tried something like that:
```latex
\sectionTitle{title}{\faTasks}
\begin{minipage}[t]{\dimexpr(\linewidth/2) - 3em}
    first column content
  \end{minipage}
  \hfill
  \begin{minipage}[t]{\dimexpr(\linewidth/2) - 3em}
    second column content
  \end{minipage}
  }
```

Does that work ?

**Comment by pbisaria007** [comment]
> 
> 
> Hi,
> 
> I would have tried something like that:
> 
> ```
> \sectionTitle{title}{\faTasks}
> \begin{minipage}[t]{\dimexpr(\linewidth/2) - 3em}
>     first column content
>   \end{minipage}
>   \hfill
>   \begin{minipage}[t]{\dimexpr(\linewidth/2) - 3em}
>     second column content
>   \end{minipage}
>   }
> ```
> 
> Does that work ?

**Comment by pbisaria007** [comment]
>   \begin{minipage}[t]{\dimexpr(\linewidth/2) - 3em}

No, it's not working.
![slide-1-638](https://user-images.githubusercontent.com/44259814/84994519-6eb08a00-b168-11ea-8b29-d749fa907af9.jpg)
 i want to do something like this, same section having two column body
