### ISSUE TITLE
StackOverflow social network not render a clickable link

### ISSUE THREAD

**Issue by davidvasquezr** [darwiin/yaac-another-awesome-cv#61]
I have the SO command inside `\socialinfo`:

```
\socialinfo{
	\smartphone{1111111}
	\email{email@gmail.com}\\
    \linkedin{david-jesús-vásquez-rios-b76583ba/}\\
    \stackoverflow{5869384}
}

\makecvheader
```

But only Github clickable link is rendering ok.

![image](https://user-images.githubusercontent.com/18266371/98705037-49a4f980-234b-11eb-8ae7-858cbc811c8e.png)

**Comment by itrich** [comment]
This works perfectly for me:
`\stackoverflow{6532156} \\` generates:  ![2021-01-24 20_06_36-CV - Online LaTeX Editor Overleaf](https://user-images.githubusercontent.com/29982899/105640728-bc6c3e00-5e7f-11eb-973c-0f5295a774b5.png)

Have you double-checked, that your `yaac-another-awesome-cv.cls` contains this code:
```
% Render author's stackoverflow profile (optional)
% Usage: \stackoverflow{<stackoverflow-user-id>}
\newcommand*{\stackoverflow}[1]{\sociallink{\stackoverflowSymbol}{https://www.stackoverflow.com/u/#1}{stackoverflow.com/u/#1}}
```

**Comment by bong0** [comment]
@itrich For me at least the issue was probably related to someone not including a current version of yaac in their template at overleaf (https://www.overleaf.com/latex/templates/awesome-source-cv/wrdjtkkytqcw) 

One should instead pull the newest .cls manually from https://raw.githubusercontent.com/darwiin/yaac-another-awesome-cv/master/yaac-another-awesome-cv.cls to be sure.

**Comment by davidvasquezr** [comment]
Solved by adding icon and StackOverflow command in `.cls` file:

```
\newcommand{\stackoverflowSymbol}{\faStackOverflow}
```

```
% Render author's stackoverflow profile (optional)
% Usage: \stackoverflow{<stackoverflow-user-id>}
\newcommand*{\stackoverflow}[1]{\sociallink{\stackoverflowSymbol}{https://www.stackoverflow.com/u/#1}{stackoverflow.com/u/#1}}
```

Thanks @itrich  @bong0
