### ISSUE TITLE
make social link clickable?

### ISSUE THREAD

**Issue by PatimaDA** [darwiin/yaac-another-awesome-cv#68]
how can I make the social links clickable?

I tried both these syntaxes but I failed :(

-  \href{http://www.link.com}{clickable word}

- clickable word \url{http://www.link.com}

thanks in advance

**Comment by darwiin** [comment]
You can use. 
```
\href{http://link.com}{My awesome link} % this must work
\link{http://link.com}{My awesome link} % This should work
```
