### ISSUE TITLE
date in the footer part is showing month in French, anyone knows how to show it in English?

### ISSUE THREAD

**Issue by sebinseban** [darwiin/yaac-another-awesome-cv#71]
![image](https://user-images.githubusercontent.com/32323262/162145126-7249af64-8950-467c-8adc-461a229001a6.png)

It's printing out **Avril** instead of April on all pages.

**Comment by sebinseban** [comment]
found the solution. 
Either completely remove the french package or just modify the date only.
Both answers are in this thread
https://tex.stackexchange.com/questions/637714/current-day-using-today-for-march-give-mars

**Comment by soakes** [comment]
> found the solution. Either completely remove the french package or just modify the date only. Both answers are in this thread https://tex.stackexchange.com/questions/637714/current-day-using-today-for-march-give-mars

Thank you @sebinseban  for providing the solution.  This works perfectly by adding in the following to convert it to english.
`{\selectlanguage{english}\textsc{\today}}`
