### ISSUE TITLE
projects section

### ISSUE THREAD

**Issue by sarora** [darwiin/yaac-another-awesome-cv#9]
Hi Christophe,

Many thanks for an amazing and a professional template. Is it possible to make a projects section for the template? Something where I can add a title, GitHub link, date, give a short description (point format) of the project? Please let me know if you want more details. 

Thanks,
Sid

**Comment by darwiin** [comment]
Hi Sid,

Thanks for your message. This is a great idea. I'll try to work on that subject this week. If you have an idea of how to organize the project layout, feel free to attach a mockup as a new comment to this issue.

**Comment by sarora** [comment]
Hi Christophe,

Thanks for your reply. I was thinking it to be similar to your experience section (to maintain consistency) with an added provision of a Github link. So the job title becomes the project title,  etc. 

Infact, it will be cool if we can make the company name in the experience section a clickable link (recruiters can go and click on the link). Sorry, not creating a separate issue for that. Please let me know if you need more details.

**Comment by darwiin** [comment]
Hi Sid,
I finally had time to add a project macro. Sorry for the delay, I was very busy the last month.

Christophe.

**Comment by darwiin** [comment]
For the Company name, feel free to replace the company name with the folowing macro `\website{link}{label}`
